heat_template_version: 2013-05-23
description: Single compute instance running Fedora in a Docker container.
parameters:
  image_name:
    type: string
  key_name:
    type: string
resources:
  my_instance:
    type: OS::Nova::Server
    properties:
      key_name: {get_param: key_name}
      availability_zone: docker
      image: {get_param: image_name}
      flavor: m1.medium
      user_data: #include https://get.docker.io
      networks: 2d5929b5-aaec-47ae-b38c-55a51a32f088 
  my_docker_container:
    type: DockerInc::Docker::Container
    properties:
      docker_endpoint: { get_attr: [my_instance, first_address] }
      image: {get_param: image_name}
